# Generated by Django 4.2.20 on 2025-03-28 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('loan_amount', models.FloatField()),
                ('property_value', models.FloatField()),
                ('annual_income', models.FloatField()),
                ('debt_amount', models.FloatField()),
                ('loan_type', models.CharField(choices=[('fixed', 'Fixed'), ('adjustable', 'Adjustable')], max_length=100)),
                ('property_type', models.CharField(choices=[('single_family', 'Single Family'), ('condo', 'Condo')], max_length=100)),
                ('credit_rating', models.CharField(blank=True, choices=[('AAA', 'AAA'), ('BBB', 'BBB'), ('C', 'C')], max_length=100)),
            ],
        ),
    ]
