# Generated by Django 4.2.20 on 2025-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
